### ISSUE TITLE
Missing default menurole on register

### ISSUE THREAD

**Issue by slothstronaut** [coreui/coreui-free-vue-laravel-admin-template#11]
I got a SQL error when trying to initially register on PHP7.4/MySQL 8 

It was missing a default value for `menuroles`

Fixed it by adding:
```
$user->menuroles = 'admin';
```

in `AuthController.php::register()`

**Comment by rakieta2015** [comment]
Thank you for your help in developing our project. The error has been fixed in the release [1.0.1](https://github.com/coreui/coreui-free-vue-laravel-admin-template/releases/tag/1.0.1)
