### ISSUE TITLE
Nesting menu in dropdown

### ISSUE THREAD

**Issue by justinbeatz** [coreui/coreui-free-vue-laravel-admin-template#19]
How you could add nested menu items, for example 3 levels on dropdown in MenuTableSeeder.php?

-First Level
-- Second Level
     -- Third Level (Parent is Second Level).

**Comment by rakieta2015** [comment]
$this->beginDropdown('user,admin', 'First level', 'cil-bell');
    $this->insertLink('user,admin', 'First level link',     '/notifications/alerts');
    $this->beginDropdown('user,admin', 'Second level', 'cil-bell');
        $this->insertLink('user,admin', 'Second level link',     '/notifications/alerts');
        $this->beginDropdown('user,admin', 'Last level', 'cil-bell');
            $this->insertLink('user,admin', 'Last level link',     '/notifications/alerts');
        $this->endDropdown();
    $this->endDropdown();
$this->endDropdown();

**Comment by justinbeatz** [comment]
Thanks.
