### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by c-myers1** [coreui/coreui-free-vue-laravel-admin-template#24]
What do I do about the error below:
    
    Migrating: 2020_01_21_150250_create_media_table
    
       Illuminate\Database\QueryException

      SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in y
    our SQL syntax; check the manual that corresponds to your MariaDB server version
     for the right syntax to use near 'json not null, `custom_properties` json not n
    ull, `responsive_images` json not n' at line 1 (SQL: create table `media` (`id`
    bigint unsigned not null auto_increment primary key, `model_type` varchar(191) n
    ot null, `model_id` bigint unsigned not null, `collection_name` varchar(191) not
     null, `name` varchar(191) not null, `file_name` varchar(191) not null, `mime_ty
    pe` varchar(191) null, `disk` varchar(191) not null, `conversions_disk` varchar(
    191) not null, `size` bigint unsigned not null, `uuid` bigint unsigned not null,
     `manipulations` json not null, `custom_properties` json not null, `responsive_i
    mages` json not null, `order_column` int unsigned null, `created_at` timestamp n
    ull, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4
    _unicode_ci')

**Comment by justinbeatz** [comment]
Check your mysql/mariadb version for json compatibility. JSON was added in mysql 5.7 and MariaDB 10.2.7.

**Comment by c-myers1** [comment]
@justinbeatz : thanks, this resolved it
